[package]
name = "alchemy"
version = "0.1.0"
authors = ["Lain <lain@lain.org.uk>"]
build = "build.rs"

[lib]
crate-type = ["staticlib"]
doc = true

[dependencies]
rlibc = "1.0.0"

[dependencies.spin]
version = "0.4.3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"